In [0]:
import numpy as np

In [2]:
an_arr = np.array(["Hello", "World"])
an_arr = np.append(an_arr, "!")
print(an_arr)

for element in an_arr:
  print(element)

for index, element in enumerate(an_arr):
  print(index, "--", element)

print(type(an_arr))

['Hello' 'World' '!']
Hello
World
!
0 -- Hello
1 -- World
2 -- !
<class 'numpy.ndarray'>


In [3]:
arr_1 = np.array([0, 1, 100, 5, -2, -30])
print(arr_1)

print("Max : {}".format(np.max(arr_1)))
print("Min : {}".format(np.min(arr_1)))
print("Max index : {}".format(np.argmax(arr_1)))
print("Min index : {}".format(np.argmin(arr_1)))
print("Average : {}".format(np.average(arr_1)))

[  0   1 100   5  -2 -30]
Max : 100
Min : -30
Max index : 2
Min index : 5
Average : 12.333333333333334


In [4]:
print(type(an_arr), "  ", type(an_arr[0]))
print(type(arr_1), "  ", type(arr_1[0]))

<class 'numpy.ndarray'>    <class 'numpy.str_'>
<class 'numpy.ndarray'>    <class 'numpy.int64'>


In [5]:
rand_arr_1 = np.random.rand(3, 4)
print(rand_arr_1, "\n")

for row in rand_arr_1:
  print()
  print(row)
  for col in row:
    print(col)
  
print("\nShape of an_arr : {}".format(an_arr.shape))
print("Shape of arr_1 : {}".format(arr_1.shape))
print("Shape of rand_arr_1 : {}".format(rand_arr_1.shape))

[[0.77117151 0.12906853 0.93977916 0.48929272]
 [0.93101947 0.48827797 0.62489812 0.82969205]
 [0.78347164 0.75311931 0.6442493  0.62936155]] 


[0.77117151 0.12906853 0.93977916 0.48929272]
0.7711715129560741
0.1290685331170055
0.9397791577568595
0.4892927216637736

[0.93101947 0.48827797 0.62489812 0.82969205]
0.9310194711349886
0.48827796954236735
0.6248981221470145
0.8296920549941242

[0.78347164 0.75311931 0.6442493  0.62936155]
0.7834716353981694
0.7531193068912693
0.6442493034078323
0.6293615543636522

Shape of an_arr : (3,)
Shape of arr_1 : (6,)
Shape of rand_arr_1 : (3, 4)
